# Generated by Django 5.2.1 on 2025-05-07 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firma', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('plz', models.IntegerField()),
                ('ort', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lohnart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Taetigkeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vertragsart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Standort',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bezeichnung', models.CharField(max_length=100)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standorte', to='vertrag.firma')),
            ],
        ),
        migrations.CreateModel(
            name='Vertrag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mitarbeiter', models.CharField(max_length=100)),
                ('mitarbeiter_adresse', models.CharField(max_length=100)),
                ('mitarbeiter_plz', models.IntegerField()),
                ('mitarbeiter_ort', models.CharField(max_length=100)),
                ('beginn', models.DateField()),
                ('arbeitsstunden', models.DecimalField(decimal_places=2, max_digits=10)),
                ('urlaub', models.CharField(max_length=100)),
                ('einsatzort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vertrag.standort')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vertrag.firma')),
                ('lohnart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vertrag.lohnart')),
                ('taetigkeit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vertrag.taetigkeit')),
                ('vertragsart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vertrag.vertragsart')),
            ],
        ),
    ]
